#ifndef QUICKJS_IMGUI_CONSTANTS_HPP
#define QUICKJS_IMGUI_CONSTANTS_HPP

static const JSCFunctionListEntry js_imgui_window_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiWindowFlags_None, 0),
    JS_PROP_INT32_DEF("NoTitleBar", ImGuiWindowFlags_NoTitleBar, 0),
    JS_PROP_INT32_DEF("NoResize", ImGuiWindowFlags_NoResize, 0),
    JS_PROP_INT32_DEF("NoMove", ImGuiWindowFlags_NoMove, 0),
    JS_PROP_INT32_DEF("NoScrollbar", ImGuiWindowFlags_NoScrollbar, 0),
    JS_PROP_INT32_DEF("NoScrollWithMouse", ImGuiWindowFlags_NoScrollWithMouse, 0),
    JS_PROP_INT32_DEF("NoCollapse", ImGuiWindowFlags_NoCollapse, 0),
    JS_PROP_INT32_DEF("AlwaysAutoResize", ImGuiWindowFlags_AlwaysAutoResize, 0),
    JS_PROP_INT32_DEF("NoBackground", ImGuiWindowFlags_NoBackground, 0),
    JS_PROP_INT32_DEF("NoSavedSettings", ImGuiWindowFlags_NoSavedSettings, 0),
    JS_PROP_INT32_DEF("NoMouseInputs", ImGuiWindowFlags_NoMouseInputs, 0),
    JS_PROP_INT32_DEF("MenuBar", ImGuiWindowFlags_MenuBar, 0),
    JS_PROP_INT32_DEF("HorizontalScrollbar", ImGuiWindowFlags_HorizontalScrollbar, 0),
    JS_PROP_INT32_DEF("NoFocusOnAppearing", ImGuiWindowFlags_NoFocusOnAppearing, 0),
    JS_PROP_INT32_DEF("NoBringToFrontOnFocus", ImGuiWindowFlags_NoBringToFrontOnFocus, 0),
    JS_PROP_INT32_DEF("AlwaysVerticalScrollbar", ImGuiWindowFlags_AlwaysVerticalScrollbar, 0),
    JS_PROP_INT32_DEF("AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar, 0),
    JS_PROP_INT32_DEF("AlwaysUseWindowPadding", ImGuiWindowFlags_AlwaysUseWindowPadding, 0),
    JS_PROP_INT32_DEF("NoNavInputs", ImGuiWindowFlags_NoNavInputs, 0),
    JS_PROP_INT32_DEF("NoNavFocus", ImGuiWindowFlags_NoNavFocus, 0),
    JS_PROP_INT32_DEF("UnsavedDocument", ImGuiWindowFlags_UnsavedDocument, 0),
    JS_PROP_INT32_DEF("NoNav", ImGuiWindowFlags_NoNav, 0),
    JS_PROP_INT32_DEF("NoDecoration", ImGuiWindowFlags_NoDecoration, 0),
    JS_PROP_INT32_DEF("NoInputs", ImGuiWindowFlags_NoInputs, 0),
    JS_PROP_INT32_DEF("NavFlattened", ImGuiWindowFlags_NavFlattened, 0),
    JS_PROP_INT32_DEF("ChildWindow", ImGuiWindowFlags_ChildWindow, 0),
    JS_PROP_INT32_DEF("Tooltip", ImGuiWindowFlags_Tooltip, 0),
    JS_PROP_INT32_DEF("Popup", ImGuiWindowFlags_Popup, 0),
    JS_PROP_INT32_DEF("Modal", ImGuiWindowFlags_Modal, 0),
    JS_PROP_INT32_DEF("ChildMenu", ImGuiWindowFlags_ChildMenu, 0),
};

static const JSCFunctionListEntry js_imgui_inputtext_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiInputTextFlags_None, 0),
    JS_PROP_INT32_DEF("CharsDecimal", ImGuiInputTextFlags_CharsDecimal, 0),
    JS_PROP_INT32_DEF("CharsHexadecimal", ImGuiInputTextFlags_CharsHexadecimal, 0),
    JS_PROP_INT32_DEF("CharsUppercase", ImGuiInputTextFlags_CharsUppercase, 0),
    JS_PROP_INT32_DEF("CharsNoBlank", ImGuiInputTextFlags_CharsNoBlank, 0),
    JS_PROP_INT32_DEF("AutoSelectAll", ImGuiInputTextFlags_AutoSelectAll, 0),
    JS_PROP_INT32_DEF("EnterReturnsTrue", ImGuiInputTextFlags_EnterReturnsTrue, 0),
    JS_PROP_INT32_DEF("CallbackCompletion", ImGuiInputTextFlags_CallbackCompletion, 0),
    JS_PROP_INT32_DEF("CallbackHistory", ImGuiInputTextFlags_CallbackHistory, 0),
    JS_PROP_INT32_DEF("CallbackAlways", ImGuiInputTextFlags_CallbackAlways, 0),
    JS_PROP_INT32_DEF("CallbackCharFilter", ImGuiInputTextFlags_CallbackCharFilter, 0),
    JS_PROP_INT32_DEF("AllowTabInput", ImGuiInputTextFlags_AllowTabInput, 0),
    JS_PROP_INT32_DEF("CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine, 0),
    JS_PROP_INT32_DEF("NoHorizontalScroll", ImGuiInputTextFlags_NoHorizontalScroll, 0),
    JS_PROP_INT32_DEF("AlwaysOverwrite", ImGuiInputTextFlags_AlwaysOverwrite, 0),
    JS_PROP_INT32_DEF("ReadOnly", ImGuiInputTextFlags_ReadOnly, 0),
    JS_PROP_INT32_DEF("Password", ImGuiInputTextFlags_Password, 0),
    JS_PROP_INT32_DEF("NoUndoRedo", ImGuiInputTextFlags_NoUndoRedo, 0),
    JS_PROP_INT32_DEF("CharsScientific", ImGuiInputTextFlags_CharsScientific, 0),
    JS_PROP_INT32_DEF("CallbackResize", ImGuiInputTextFlags_CallbackResize, 0),
    JS_PROP_INT32_DEF("CallbackEdit", ImGuiInputTextFlags_CallbackEdit, 0),
};

static const JSCFunctionListEntry js_imgui_treenode_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTreeNodeFlags_None, 0),
    JS_PROP_INT32_DEF("Selected", ImGuiTreeNodeFlags_Selected, 0),
    JS_PROP_INT32_DEF("Framed", ImGuiTreeNodeFlags_Framed, 0),
    JS_PROP_INT32_DEF("AllowItemOverlap", ImGuiTreeNodeFlags_AllowItemOverlap, 0),
    JS_PROP_INT32_DEF("NoTreePushOnOpen", ImGuiTreeNodeFlags_NoTreePushOnOpen, 0),
    JS_PROP_INT32_DEF("NoAutoOpenOnLog", ImGuiTreeNodeFlags_NoAutoOpenOnLog, 0),
    JS_PROP_INT32_DEF("DefaultOpen", ImGuiTreeNodeFlags_DefaultOpen, 0),
    JS_PROP_INT32_DEF("OpenOnDoubleClick", ImGuiTreeNodeFlags_OpenOnDoubleClick, 0),
    JS_PROP_INT32_DEF("OpenOnArrow", ImGuiTreeNodeFlags_OpenOnArrow, 0),
    JS_PROP_INT32_DEF("Leaf", ImGuiTreeNodeFlags_Leaf, 0),
    JS_PROP_INT32_DEF("Bullet", ImGuiTreeNodeFlags_Bullet, 0),
    JS_PROP_INT32_DEF("FramePadding", ImGuiTreeNodeFlags_FramePadding, 0),
    JS_PROP_INT32_DEF("SpanAvailWidth", ImGuiTreeNodeFlags_SpanAvailWidth, 0),
    JS_PROP_INT32_DEF("SpanFullWidth", ImGuiTreeNodeFlags_SpanFullWidth, 0),
    JS_PROP_INT32_DEF("NavLeftJumpsBackHere", ImGuiTreeNodeFlags_NavLeftJumpsBackHere, 0),
    JS_PROP_INT32_DEF("CollapsingHeader", ImGuiTreeNodeFlags_CollapsingHeader, 0),
};

static const JSCFunctionListEntry js_imgui_popup_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiPopupFlags_None, 0),
    JS_PROP_INT32_DEF("MouseButtonLeft", ImGuiPopupFlags_MouseButtonLeft, 0),
    JS_PROP_INT32_DEF("MouseButtonRight", ImGuiPopupFlags_MouseButtonRight, 0),
    JS_PROP_INT32_DEF("MouseButtonMiddle", ImGuiPopupFlags_MouseButtonMiddle, 0),
    JS_PROP_INT32_DEF("MouseButtonMask_", ImGuiPopupFlags_MouseButtonMask_, 0),
    JS_PROP_INT32_DEF("MouseButtonDefault_", ImGuiPopupFlags_MouseButtonDefault_, 0),
    JS_PROP_INT32_DEF("NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup, 0),
    JS_PROP_INT32_DEF("NoOpenOverItems", ImGuiPopupFlags_NoOpenOverItems, 0),
    JS_PROP_INT32_DEF("AnyPopupId", ImGuiPopupFlags_AnyPopupId, 0),
    JS_PROP_INT32_DEF("AnyPopupLevel", ImGuiPopupFlags_AnyPopupLevel, 0),
    JS_PROP_INT32_DEF("AnyPopup", ImGuiPopupFlags_AnyPopup, 0),
};

static const JSCFunctionListEntry js_imgui_selectable_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiSelectableFlags_None, 0),
    JS_PROP_INT32_DEF("DontClosePopups", ImGuiSelectableFlags_DontClosePopups, 0),
    JS_PROP_INT32_DEF("SpanAllColumns", ImGuiSelectableFlags_SpanAllColumns, 0),
    JS_PROP_INT32_DEF("AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick, 0),
    JS_PROP_INT32_DEF("Disabled", ImGuiSelectableFlags_Disabled, 0),
    JS_PROP_INT32_DEF("AllowItemOverlap", ImGuiSelectableFlags_AllowItemOverlap, 0),
};

static const JSCFunctionListEntry js_imgui_combo_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiComboFlags_None, 0),
    JS_PROP_INT32_DEF("PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft, 0),
    JS_PROP_INT32_DEF("HeightSmall", ImGuiComboFlags_HeightSmall, 0),
    JS_PROP_INT32_DEF("HeightRegular", ImGuiComboFlags_HeightRegular, 0),
    JS_PROP_INT32_DEF("HeightLarge", ImGuiComboFlags_HeightLarge, 0),
    JS_PROP_INT32_DEF("HeightLargest", ImGuiComboFlags_HeightLargest, 0),
    JS_PROP_INT32_DEF("NoArrowButton", ImGuiComboFlags_NoArrowButton, 0),
    JS_PROP_INT32_DEF("NoPreview", ImGuiComboFlags_NoPreview, 0),
    JS_PROP_INT32_DEF("HeightMask_", ImGuiComboFlags_HeightMask_, 0),
};

static const JSCFunctionListEntry js_imgui_tabbar_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTabBarFlags_None, 0),
    JS_PROP_INT32_DEF("Reorderable", ImGuiTabBarFlags_Reorderable, 0),
    JS_PROP_INT32_DEF("AutoSelectNewTabs", ImGuiTabBarFlags_AutoSelectNewTabs, 0),
    JS_PROP_INT32_DEF("TabListPopupButton", ImGuiTabBarFlags_TabListPopupButton, 0),
    JS_PROP_INT32_DEF("NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton, 0),
    JS_PROP_INT32_DEF("NoTabListScrollingButtons", ImGuiTabBarFlags_NoTabListScrollingButtons, 0),
    JS_PROP_INT32_DEF("NoTooltip", ImGuiTabBarFlags_NoTooltip, 0),
    JS_PROP_INT32_DEF("FittingPolicyResizeDown", ImGuiTabBarFlags_FittingPolicyResizeDown, 0),
    JS_PROP_INT32_DEF("FittingPolicyScroll", ImGuiTabBarFlags_FittingPolicyScroll, 0),
    JS_PROP_INT32_DEF("FittingPolicyMask_", ImGuiTabBarFlags_FittingPolicyMask_, 0),
    JS_PROP_INT32_DEF("FittingPolicyDefault_", ImGuiTabBarFlags_FittingPolicyDefault_, 0),
};

static const JSCFunctionListEntry js_imgui_tabitem_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTabItemFlags_None, 0),
    JS_PROP_INT32_DEF("UnsavedDocument", ImGuiTabItemFlags_UnsavedDocument, 0),
    JS_PROP_INT32_DEF("SetSelected", ImGuiTabItemFlags_SetSelected, 0),
    JS_PROP_INT32_DEF("NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton, 0),
    JS_PROP_INT32_DEF("NoPushId", ImGuiTabItemFlags_NoPushId, 0),
    JS_PROP_INT32_DEF("NoTooltip", ImGuiTabItemFlags_NoTooltip, 0),
    JS_PROP_INT32_DEF("NoReorder", ImGuiTabItemFlags_NoReorder, 0),
    JS_PROP_INT32_DEF("Leading", ImGuiTabItemFlags_Leading, 0),
    JS_PROP_INT32_DEF("Trailing", ImGuiTabItemFlags_Trailing, 0),
};

static const JSCFunctionListEntry js_imgui_table_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTableFlags_None, 0),
    JS_PROP_INT32_DEF("Resizable", ImGuiTableFlags_Resizable, 0),
    JS_PROP_INT32_DEF("Reorderable", ImGuiTableFlags_Reorderable, 0),
    JS_PROP_INT32_DEF("Hideable", ImGuiTableFlags_Hideable, 0),
    JS_PROP_INT32_DEF("Sortable", ImGuiTableFlags_Sortable, 0),
    JS_PROP_INT32_DEF("NoSavedSettings", ImGuiTableFlags_NoSavedSettings, 0),
    JS_PROP_INT32_DEF("ContextMenuInBody", ImGuiTableFlags_ContextMenuInBody, 0),
    JS_PROP_INT32_DEF("RowBg", ImGuiTableFlags_RowBg, 0),
    JS_PROP_INT32_DEF("BordersInnerH", ImGuiTableFlags_BordersInnerH, 0),
    JS_PROP_INT32_DEF("BordersOuterH", ImGuiTableFlags_BordersOuterH, 0),
    JS_PROP_INT32_DEF("BordersInnerV", ImGuiTableFlags_BordersInnerV, 0),
    JS_PROP_INT32_DEF("BordersOuterV", ImGuiTableFlags_BordersOuterV, 0),
    JS_PROP_INT32_DEF("BordersH", ImGuiTableFlags_BordersH, 0),
    JS_PROP_INT32_DEF("BordersV", ImGuiTableFlags_BordersV, 0),
    JS_PROP_INT32_DEF("BordersInner", ImGuiTableFlags_BordersInner, 0),
    JS_PROP_INT32_DEF("BordersOuter", ImGuiTableFlags_BordersOuter, 0),
    JS_PROP_INT32_DEF("Borders", ImGuiTableFlags_Borders, 0),
    JS_PROP_INT32_DEF("NoBordersInBody", ImGuiTableFlags_NoBordersInBody, 0),
    JS_PROP_INT32_DEF("NoBordersInBodyUntilResize", ImGuiTableFlags_NoBordersInBodyUntilResize, 0),
    JS_PROP_INT32_DEF("SizingFixedFit", ImGuiTableFlags_SizingFixedFit, 0),
    JS_PROP_INT32_DEF("SizingFixedSame", ImGuiTableFlags_SizingFixedSame, 0),
    JS_PROP_INT32_DEF("SizingStretchProp", ImGuiTableFlags_SizingStretchProp, 0),
    JS_PROP_INT32_DEF("SizingStretchSame", ImGuiTableFlags_SizingStretchSame, 0),
    JS_PROP_INT32_DEF("NoHostExtendX", ImGuiTableFlags_NoHostExtendX, 0),
    JS_PROP_INT32_DEF("NoHostExtendY", ImGuiTableFlags_NoHostExtendY, 0),
    JS_PROP_INT32_DEF("NoKeepColumnsVisible", ImGuiTableFlags_NoKeepColumnsVisible, 0),
    JS_PROP_INT32_DEF("PreciseWidths", ImGuiTableFlags_PreciseWidths, 0),
    JS_PROP_INT32_DEF("NoClip", ImGuiTableFlags_NoClip, 0),
    JS_PROP_INT32_DEF("PadOuterX", ImGuiTableFlags_PadOuterX, 0),
    JS_PROP_INT32_DEF("NoPadOuterX", ImGuiTableFlags_NoPadOuterX, 0),
    JS_PROP_INT32_DEF("NoPadInnerX", ImGuiTableFlags_NoPadInnerX, 0),
    JS_PROP_INT32_DEF("ScrollX", ImGuiTableFlags_ScrollX, 0),
    JS_PROP_INT32_DEF("ScrollY", ImGuiTableFlags_ScrollY, 0),
    JS_PROP_INT32_DEF("SortMulti", ImGuiTableFlags_SortMulti, 0),
    JS_PROP_INT32_DEF("SortTristate", ImGuiTableFlags_SortTristate, 0),
    JS_PROP_INT32_DEF("SizingMask_", ImGuiTableFlags_SizingMask_, 0),
};

static const JSCFunctionListEntry js_imgui_tablecolumn_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTableColumnFlags_None, 0),
    JS_PROP_INT32_DEF("Disabled", ImGuiTableColumnFlags_Disabled, 0),
    JS_PROP_INT32_DEF("DefaultHide", ImGuiTableColumnFlags_DefaultHide, 0),
    JS_PROP_INT32_DEF("DefaultSort", ImGuiTableColumnFlags_DefaultSort, 0),
    JS_PROP_INT32_DEF("WidthStretch", ImGuiTableColumnFlags_WidthStretch, 0),
    JS_PROP_INT32_DEF("WidthFixed", ImGuiTableColumnFlags_WidthFixed, 0),
    JS_PROP_INT32_DEF("NoResize", ImGuiTableColumnFlags_NoResize, 0),
    JS_PROP_INT32_DEF("NoReorder", ImGuiTableColumnFlags_NoReorder, 0),
    JS_PROP_INT32_DEF("NoHide", ImGuiTableColumnFlags_NoHide, 0),
    JS_PROP_INT32_DEF("NoClip", ImGuiTableColumnFlags_NoClip, 0),
    JS_PROP_INT32_DEF("NoSort", ImGuiTableColumnFlags_NoSort, 0),
    JS_PROP_INT32_DEF("NoSortAscending", ImGuiTableColumnFlags_NoSortAscending, 0),
    JS_PROP_INT32_DEF("NoSortDescending", ImGuiTableColumnFlags_NoSortDescending, 0),
    JS_PROP_INT32_DEF("NoHeaderLabel", ImGuiTableColumnFlags_NoHeaderLabel, 0),
    JS_PROP_INT32_DEF("NoHeaderWidth", ImGuiTableColumnFlags_NoHeaderWidth, 0),
    JS_PROP_INT32_DEF("PreferSortAscending", ImGuiTableColumnFlags_PreferSortAscending, 0),
    JS_PROP_INT32_DEF("PreferSortDescending", ImGuiTableColumnFlags_PreferSortDescending, 0),
    JS_PROP_INT32_DEF("IndentEnable", ImGuiTableColumnFlags_IndentEnable, 0),
    JS_PROP_INT32_DEF("IndentDisable", ImGuiTableColumnFlags_IndentDisable, 0),
    JS_PROP_INT32_DEF("IsEnabled", ImGuiTableColumnFlags_IsEnabled, 0),
    JS_PROP_INT32_DEF("IsVisible", ImGuiTableColumnFlags_IsVisible, 0),
    JS_PROP_INT32_DEF("IsSorted", ImGuiTableColumnFlags_IsSorted, 0),
    JS_PROP_INT32_DEF("IsHovered", ImGuiTableColumnFlags_IsHovered, 0),
    JS_PROP_INT32_DEF("WidthMask_", ImGuiTableColumnFlags_WidthMask_, 0),
    JS_PROP_INT32_DEF("IndentMask_", ImGuiTableColumnFlags_IndentMask_, 0),
    JS_PROP_INT32_DEF("StatusMask_", ImGuiTableColumnFlags_StatusMask_, 0),
    JS_PROP_INT32_DEF("NoDirectResize_", ImGuiTableColumnFlags_NoDirectResize_, 0),
};

static const JSCFunctionListEntry js_imgui_tablerow_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiTableRowFlags_None, 0),
    JS_PROP_INT32_DEF("Headers", ImGuiTableRowFlags_Headers, 0),
};

static const JSCFunctionListEntry js_imgui_tablebgtarget[] = {
    JS_PROP_INT32_DEF("None", ImGuiTableBgTarget_None, 0),
    JS_PROP_INT32_DEF("RowBg0", ImGuiTableBgTarget_RowBg0, 0),
    JS_PROP_INT32_DEF("RowBg1", ImGuiTableBgTarget_RowBg1, 0),
    JS_PROP_INT32_DEF("CellBg", ImGuiTableBgTarget_CellBg, 0),
};

static const JSCFunctionListEntry js_imgui_focused_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiFocusedFlags_None, 0),
    JS_PROP_INT32_DEF("ChildWindows", ImGuiFocusedFlags_ChildWindows, 0),
    JS_PROP_INT32_DEF("RootWindow", ImGuiFocusedFlags_RootWindow, 0),
    JS_PROP_INT32_DEF("AnyWindow", ImGuiFocusedFlags_AnyWindow, 0),
    JS_PROP_INT32_DEF("RootAndChildWindows", ImGuiFocusedFlags_RootAndChildWindows, 0),
};

static const JSCFunctionListEntry js_imgui_hovered_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiHoveredFlags_None, 0),
    JS_PROP_INT32_DEF("ChildWindows", ImGuiHoveredFlags_ChildWindows, 0),
    JS_PROP_INT32_DEF("RootWindow", ImGuiHoveredFlags_RootWindow, 0),
    JS_PROP_INT32_DEF("AnyWindow", ImGuiHoveredFlags_AnyWindow, 0),
    JS_PROP_INT32_DEF("AllowWhenBlockedByPopup", ImGuiHoveredFlags_AllowWhenBlockedByPopup, 0),
    JS_PROP_INT32_DEF("AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, 0),
    JS_PROP_INT32_DEF("AllowWhenOverlapped", ImGuiHoveredFlags_AllowWhenOverlapped, 0),
    JS_PROP_INT32_DEF("AllowWhenDisabled", ImGuiHoveredFlags_AllowWhenDisabled, 0),
    JS_PROP_INT32_DEF("RectOnly", ImGuiHoveredFlags_RectOnly, 0),
    JS_PROP_INT32_DEF("RootAndChildWindows", ImGuiHoveredFlags_RootAndChildWindows, 0),
};

static const JSCFunctionListEntry js_imgui_dragdrop_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiDragDropFlags_None, 0),
    JS_PROP_INT32_DEF("SourceNoPreviewTooltip", ImGuiDragDropFlags_SourceNoPreviewTooltip, 0),
    JS_PROP_INT32_DEF("SourceNoDisableHover", ImGuiDragDropFlags_SourceNoDisableHover, 0),
    JS_PROP_INT32_DEF("SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers, 0),
    JS_PROP_INT32_DEF("SourceAllowNullID", ImGuiDragDropFlags_SourceAllowNullID, 0),
    JS_PROP_INT32_DEF("SourceExtern", ImGuiDragDropFlags_SourceExtern, 0),
    JS_PROP_INT32_DEF("SourceAutoExpirePayload", ImGuiDragDropFlags_SourceAutoExpirePayload, 0),
    JS_PROP_INT32_DEF("AcceptBeforeDelivery", ImGuiDragDropFlags_AcceptBeforeDelivery, 0),
    JS_PROP_INT32_DEF("AcceptNoDrawDefaultRect", ImGuiDragDropFlags_AcceptNoDrawDefaultRect, 0),
    JS_PROP_INT32_DEF("AcceptNoPreviewTooltip", ImGuiDragDropFlags_AcceptNoPreviewTooltip, 0),
    JS_PROP_INT32_DEF("AcceptPeekOnly", ImGuiDragDropFlags_AcceptPeekOnly, 0),
};

static const JSCFunctionListEntry js_imgui_datatype[] = {
    JS_PROP_INT32_DEF("S8", ImGuiDataType_S8, 0),
    JS_PROP_INT32_DEF("U8", ImGuiDataType_U8, 0),
    JS_PROP_INT32_DEF("S16", ImGuiDataType_S16, 0),
    JS_PROP_INT32_DEF("U16", ImGuiDataType_U16, 0),
    JS_PROP_INT32_DEF("S32", ImGuiDataType_S32, 0),
    JS_PROP_INT32_DEF("U32", ImGuiDataType_U32, 0),
    JS_PROP_INT32_DEF("S64", ImGuiDataType_S64, 0),
    JS_PROP_INT32_DEF("U64", ImGuiDataType_U64, 0),
    JS_PROP_INT32_DEF("Float", ImGuiDataType_Float, 0),
    JS_PROP_INT32_DEF("Double", ImGuiDataType_Double, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiDataType_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_dir[] = {
    JS_PROP_INT32_DEF("None", ImGuiDir_None, 0),
    JS_PROP_INT32_DEF("Left", ImGuiDir_Left, 0),
    JS_PROP_INT32_DEF("Right", ImGuiDir_Right, 0),
    JS_PROP_INT32_DEF("Up", ImGuiDir_Up, 0),
    JS_PROP_INT32_DEF("Down", ImGuiDir_Down, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiDir_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_sortdirection[] = {
    JS_PROP_INT32_DEF("None", ImGuiSortDirection_None, 0),
    JS_PROP_INT32_DEF("Ascending", ImGuiSortDirection_Ascending, 0),
    JS_PROP_INT32_DEF("Descending", ImGuiSortDirection_Descending, 0),
};

static const JSCFunctionListEntry js_imgui_key[] = {
    JS_PROP_INT32_DEF("Tab", ImGuiKey_Tab, 0),
    JS_PROP_INT32_DEF("LeftArrow", ImGuiKey_LeftArrow, 0),
    JS_PROP_INT32_DEF("RightArrow", ImGuiKey_RightArrow, 0),
    JS_PROP_INT32_DEF("UpArrow", ImGuiKey_UpArrow, 0),
    JS_PROP_INT32_DEF("DownArrow", ImGuiKey_DownArrow, 0),
    JS_PROP_INT32_DEF("PageUp", ImGuiKey_PageUp, 0),
    JS_PROP_INT32_DEF("PageDown", ImGuiKey_PageDown, 0),
    JS_PROP_INT32_DEF("Home", ImGuiKey_Home, 0),
    JS_PROP_INT32_DEF("End", ImGuiKey_End, 0),
    JS_PROP_INT32_DEF("Insert", ImGuiKey_Insert, 0),
    JS_PROP_INT32_DEF("Delete", ImGuiKey_Delete, 0),
    JS_PROP_INT32_DEF("Backspace", ImGuiKey_Backspace, 0),
    JS_PROP_INT32_DEF("Space", ImGuiKey_Space, 0),
    JS_PROP_INT32_DEF("Enter", ImGuiKey_Enter, 0),
    JS_PROP_INT32_DEF("Escape", ImGuiKey_Escape, 0),
    JS_PROP_INT32_DEF("KeyPadEnter", ImGuiKey_KeyPadEnter, 0),
    JS_PROP_INT32_DEF("A", ImGuiKey_A, 0),
    JS_PROP_INT32_DEF("C", ImGuiKey_C, 0),
    JS_PROP_INT32_DEF("V", ImGuiKey_V, 0),
    JS_PROP_INT32_DEF("X", ImGuiKey_X, 0),
    JS_PROP_INT32_DEF("Y", ImGuiKey_Y, 0),
    JS_PROP_INT32_DEF("Z", ImGuiKey_Z, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiKey_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_keymod_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiKeyModFlags_None, 0),
    JS_PROP_INT32_DEF("Ctrl", ImGuiKeyModFlags_Ctrl, 0),
    JS_PROP_INT32_DEF("Shift", ImGuiKeyModFlags_Shift, 0),
    JS_PROP_INT32_DEF("Alt", ImGuiKeyModFlags_Alt, 0),
    JS_PROP_INT32_DEF("Super", ImGuiKeyModFlags_Super, 0),
};

static const JSCFunctionListEntry js_imgui_navinput[] = {
    JS_PROP_INT32_DEF("Activate", ImGuiNavInput_Activate, 0),     JS_PROP_INT32_DEF("Cancel", ImGuiNavInput_Cancel, 0),
    JS_PROP_INT32_DEF("Input", ImGuiNavInput_Input, 0),           JS_PROP_INT32_DEF("Menu", ImGuiNavInput_Menu, 0),
    JS_PROP_INT32_DEF("DpadLeft", ImGuiNavInput_DpadLeft, 0),     JS_PROP_INT32_DEF("DpadRight", ImGuiNavInput_DpadRight, 0),
    JS_PROP_INT32_DEF("DpadUp", ImGuiNavInput_DpadUp, 0),         JS_PROP_INT32_DEF("DpadDown", ImGuiNavInput_DpadDown, 0),
    JS_PROP_INT32_DEF("LStickLeft", ImGuiNavInput_LStickLeft, 0), JS_PROP_INT32_DEF("LStickRight", ImGuiNavInput_LStickRight, 0),
    JS_PROP_INT32_DEF("LStickUp", ImGuiNavInput_LStickUp, 0),     JS_PROP_INT32_DEF("LStickDown", ImGuiNavInput_LStickDown, 0),
    JS_PROP_INT32_DEF("FocusPrev", ImGuiNavInput_FocusPrev, 0),   JS_PROP_INT32_DEF("FocusNext", ImGuiNavInput_FocusNext, 0),
    JS_PROP_INT32_DEF("TweakSlow", ImGuiNavInput_TweakSlow, 0),   JS_PROP_INT32_DEF("TweakFast", ImGuiNavInput_TweakFast, 0),
    JS_PROP_INT32_DEF("KeyLeft_", ImGuiNavInput_KeyLeft_, 0),     JS_PROP_INT32_DEF("KeyRight_", ImGuiNavInput_KeyRight_, 0),
    JS_PROP_INT32_DEF("KeyUp_", ImGuiNavInput_KeyUp_, 0),         JS_PROP_INT32_DEF("KeyDown_", ImGuiNavInput_KeyDown_, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiNavInput_COUNT, 0),           JS_PROP_INT32_DEF("InternalStart_", ImGuiNavInput_InternalStart_, 0),
};

static const JSCFunctionListEntry js_imgui_config_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiConfigFlags_None, 0),
    JS_PROP_INT32_DEF("NavEnableKeyboard", ImGuiConfigFlags_NavEnableKeyboard, 0),
    JS_PROP_INT32_DEF("NavEnableGamepad", ImGuiConfigFlags_NavEnableGamepad, 0),
    JS_PROP_INT32_DEF("NavEnableSetMousePos", ImGuiConfigFlags_NavEnableSetMousePos, 0),
    JS_PROP_INT32_DEF("NavNoCaptureKeyboard", ImGuiConfigFlags_NavNoCaptureKeyboard, 0),
    JS_PROP_INT32_DEF("NoMouse", ImGuiConfigFlags_NoMouse, 0),
    JS_PROP_INT32_DEF("NoMouseCursorChange", ImGuiConfigFlags_NoMouseCursorChange, 0),
    JS_PROP_INT32_DEF("IsSRGB", ImGuiConfigFlags_IsSRGB, 0),
    JS_PROP_INT32_DEF("IsTouchScreen", ImGuiConfigFlags_IsTouchScreen, 0),
};

static const JSCFunctionListEntry js_imgui_backend_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiBackendFlags_None, 0),
    JS_PROP_INT32_DEF("HasGamepad", ImGuiBackendFlags_HasGamepad, 0),
    JS_PROP_INT32_DEF("HasMouseCursors", ImGuiBackendFlags_HasMouseCursors, 0),
    JS_PROP_INT32_DEF("HasSetMousePos", ImGuiBackendFlags_HasSetMousePos, 0),
    JS_PROP_INT32_DEF("RendererHasVtxOffset", ImGuiBackendFlags_RendererHasVtxOffset, 0),
};

static const JSCFunctionListEntry js_imgui_col[] = {
    JS_PROP_INT32_DEF("Text", ImGuiCol_Text, 0),
    JS_PROP_INT32_DEF("TextDisabled", ImGuiCol_TextDisabled, 0),
    JS_PROP_INT32_DEF("WindowBg", ImGuiCol_WindowBg, 0),
    JS_PROP_INT32_DEF("ChildBg", ImGuiCol_ChildBg, 0),
    JS_PROP_INT32_DEF("PopupBg", ImGuiCol_PopupBg, 0),
    JS_PROP_INT32_DEF("Border", ImGuiCol_Border, 0),
    JS_PROP_INT32_DEF("BorderShadow", ImGuiCol_BorderShadow, 0),
    JS_PROP_INT32_DEF("FrameBg", ImGuiCol_FrameBg, 0),
    JS_PROP_INT32_DEF("FrameBgHovered", ImGuiCol_FrameBgHovered, 0),
    JS_PROP_INT32_DEF("FrameBgActive", ImGuiCol_FrameBgActive, 0),
    JS_PROP_INT32_DEF("TitleBg", ImGuiCol_TitleBg, 0),
    JS_PROP_INT32_DEF("TitleBgActive", ImGuiCol_TitleBgActive, 0),
    JS_PROP_INT32_DEF("TitleBgCollapsed", ImGuiCol_TitleBgCollapsed, 0),
    JS_PROP_INT32_DEF("MenuBarBg", ImGuiCol_MenuBarBg, 0),
    JS_PROP_INT32_DEF("ScrollbarBg", ImGuiCol_ScrollbarBg, 0),
    JS_PROP_INT32_DEF("ScrollbarGrab", ImGuiCol_ScrollbarGrab, 0),
    JS_PROP_INT32_DEF("ScrollbarGrabHovered", ImGuiCol_ScrollbarGrabHovered, 0),
    JS_PROP_INT32_DEF("ScrollbarGrabActive", ImGuiCol_ScrollbarGrabActive, 0),
    JS_PROP_INT32_DEF("CheckMark", ImGuiCol_CheckMark, 0),
    JS_PROP_INT32_DEF("SliderGrab", ImGuiCol_SliderGrab, 0),
    JS_PROP_INT32_DEF("SliderGrabActive", ImGuiCol_SliderGrabActive, 0),
    JS_PROP_INT32_DEF("Button", ImGuiCol_Button, 0),
    JS_PROP_INT32_DEF("ButtonHovered", ImGuiCol_ButtonHovered, 0),
    JS_PROP_INT32_DEF("ButtonActive", ImGuiCol_ButtonActive, 0),
    JS_PROP_INT32_DEF("Header", ImGuiCol_Header, 0),
    JS_PROP_INT32_DEF("HeaderHovered", ImGuiCol_HeaderHovered, 0),
    JS_PROP_INT32_DEF("HeaderActive", ImGuiCol_HeaderActive, 0),
    JS_PROP_INT32_DEF("Separator", ImGuiCol_Separator, 0),
    JS_PROP_INT32_DEF("SeparatorHovered", ImGuiCol_SeparatorHovered, 0),
    JS_PROP_INT32_DEF("SeparatorActive", ImGuiCol_SeparatorActive, 0),
    JS_PROP_INT32_DEF("ResizeGrip", ImGuiCol_ResizeGrip, 0),
    JS_PROP_INT32_DEF("ResizeGripHovered", ImGuiCol_ResizeGripHovered, 0),
    JS_PROP_INT32_DEF("ResizeGripActive", ImGuiCol_ResizeGripActive, 0),
    JS_PROP_INT32_DEF("Tab", ImGuiCol_Tab, 0),
    JS_PROP_INT32_DEF("TabHovered", ImGuiCol_TabHovered, 0),
    JS_PROP_INT32_DEF("TabActive", ImGuiCol_TabActive, 0),
    JS_PROP_INT32_DEF("TabUnfocused", ImGuiCol_TabUnfocused, 0),
    JS_PROP_INT32_DEF("TabUnfocusedActive", ImGuiCol_TabUnfocusedActive, 0),
    JS_PROP_INT32_DEF("PlotLines", ImGuiCol_PlotLines, 0),
    JS_PROP_INT32_DEF("PlotLinesHovered", ImGuiCol_PlotLinesHovered, 0),
    JS_PROP_INT32_DEF("PlotHistogram", ImGuiCol_PlotHistogram, 0),
    JS_PROP_INT32_DEF("PlotHistogramHovered", ImGuiCol_PlotHistogramHovered, 0),
    JS_PROP_INT32_DEF("TableHeaderBg", ImGuiCol_TableHeaderBg, 0),
    JS_PROP_INT32_DEF("TableBorderStrong", ImGuiCol_TableBorderStrong, 0),
    JS_PROP_INT32_DEF("TableBorderLight", ImGuiCol_TableBorderLight, 0),
    JS_PROP_INT32_DEF("TableRowBg", ImGuiCol_TableRowBg, 0),
    JS_PROP_INT32_DEF("TableRowBgAlt", ImGuiCol_TableRowBgAlt, 0),
    JS_PROP_INT32_DEF("TextSelectedBg", ImGuiCol_TextSelectedBg, 0),
    JS_PROP_INT32_DEF("DragDropTarget", ImGuiCol_DragDropTarget, 0),
    JS_PROP_INT32_DEF("NavHighlight", ImGuiCol_NavHighlight, 0),
    JS_PROP_INT32_DEF("NavWindowingHighlight", ImGuiCol_NavWindowingHighlight, 0),
    JS_PROP_INT32_DEF("NavWindowingDimBg", ImGuiCol_NavWindowingDimBg, 0),
    JS_PROP_INT32_DEF("ModalWindowDimBg", ImGuiCol_ModalWindowDimBg, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiCol_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_stylevar[] = {
    JS_PROP_INT32_DEF("Alpha", ImGuiStyleVar_Alpha, 0),
    JS_PROP_INT32_DEF("DisabledAlpha", ImGuiStyleVar_DisabledAlpha, 0),
    JS_PROP_INT32_DEF("WindowPadding", ImGuiStyleVar_WindowPadding, 0),
    JS_PROP_INT32_DEF("WindowRounding", ImGuiStyleVar_WindowRounding, 0),
    JS_PROP_INT32_DEF("WindowBorderSize", ImGuiStyleVar_WindowBorderSize, 0),
    JS_PROP_INT32_DEF("WindowMinSize", ImGuiStyleVar_WindowMinSize, 0),
    JS_PROP_INT32_DEF("WindowTitleAlign", ImGuiStyleVar_WindowTitleAlign, 0),
    JS_PROP_INT32_DEF("ChildRounding", ImGuiStyleVar_ChildRounding, 0),
    JS_PROP_INT32_DEF("ChildBorderSize", ImGuiStyleVar_ChildBorderSize, 0),
    JS_PROP_INT32_DEF("PopupRounding", ImGuiStyleVar_PopupRounding, 0),
    JS_PROP_INT32_DEF("PopupBorderSize", ImGuiStyleVar_PopupBorderSize, 0),
    JS_PROP_INT32_DEF("FramePadding", ImGuiStyleVar_FramePadding, 0),
    JS_PROP_INT32_DEF("FrameRounding", ImGuiStyleVar_FrameRounding, 0),
    JS_PROP_INT32_DEF("FrameBorderSize", ImGuiStyleVar_FrameBorderSize, 0),
    JS_PROP_INT32_DEF("ItemSpacing", ImGuiStyleVar_ItemSpacing, 0),
    JS_PROP_INT32_DEF("ItemInnerSpacing", ImGuiStyleVar_ItemInnerSpacing, 0),
    JS_PROP_INT32_DEF("IndentSpacing", ImGuiStyleVar_IndentSpacing, 0),
    JS_PROP_INT32_DEF("CellPadding", ImGuiStyleVar_CellPadding, 0),
    JS_PROP_INT32_DEF("ScrollbarSize", ImGuiStyleVar_ScrollbarSize, 0),
    JS_PROP_INT32_DEF("ScrollbarRounding", ImGuiStyleVar_ScrollbarRounding, 0),
    JS_PROP_INT32_DEF("GrabMinSize", ImGuiStyleVar_GrabMinSize, 0),
    JS_PROP_INT32_DEF("GrabRounding", ImGuiStyleVar_GrabRounding, 0),
    JS_PROP_INT32_DEF("TabRounding", ImGuiStyleVar_TabRounding, 0),
    JS_PROP_INT32_DEF("ButtonTextAlign", ImGuiStyleVar_ButtonTextAlign, 0),
    JS_PROP_INT32_DEF("SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiStyleVar_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_button_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiButtonFlags_None, 0),
    JS_PROP_INT32_DEF("MouseButtonLeft", ImGuiButtonFlags_MouseButtonLeft, 0),
    JS_PROP_INT32_DEF("MouseButtonRight", ImGuiButtonFlags_MouseButtonRight, 0),
    JS_PROP_INT32_DEF("MouseButtonMiddle", ImGuiButtonFlags_MouseButtonMiddle, 0),
    JS_PROP_INT32_DEF("MouseButtonMask_", ImGuiButtonFlags_MouseButtonMask_, 0),
    JS_PROP_INT32_DEF("MouseButtonDefault_", ImGuiButtonFlags_MouseButtonDefault_, 0),
};

static const JSCFunctionListEntry js_imgui_coloredit_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiColorEditFlags_None, 0),
    JS_PROP_INT32_DEF("NoAlpha", ImGuiColorEditFlags_NoAlpha, 0),
    JS_PROP_INT32_DEF("NoPicker", ImGuiColorEditFlags_NoPicker, 0),
    JS_PROP_INT32_DEF("NoOptions", ImGuiColorEditFlags_NoOptions, 0),
    JS_PROP_INT32_DEF("NoSmallPreview", ImGuiColorEditFlags_NoSmallPreview, 0),
    JS_PROP_INT32_DEF("NoInputs", ImGuiColorEditFlags_NoInputs, 0),
    JS_PROP_INT32_DEF("NoTooltip", ImGuiColorEditFlags_NoTooltip, 0),
    JS_PROP_INT32_DEF("NoLabel", ImGuiColorEditFlags_NoLabel, 0),
    JS_PROP_INT32_DEF("NoSidePreview", ImGuiColorEditFlags_NoSidePreview, 0),
    JS_PROP_INT32_DEF("NoDragDrop", ImGuiColorEditFlags_NoDragDrop, 0),
    JS_PROP_INT32_DEF("NoBorder", ImGuiColorEditFlags_NoBorder, 0),
    JS_PROP_INT32_DEF("AlphaBar", ImGuiColorEditFlags_AlphaBar, 0),
    JS_PROP_INT32_DEF("AlphaPreview", ImGuiColorEditFlags_AlphaPreview, 0),
    JS_PROP_INT32_DEF("AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf, 0),
    JS_PROP_INT32_DEF("HDR", ImGuiColorEditFlags_HDR, 0),
    JS_PROP_INT32_DEF("DisplayRGB", ImGuiColorEditFlags_DisplayRGB, 0),
    JS_PROP_INT32_DEF("DisplayHSV", ImGuiColorEditFlags_DisplayHSV, 0),
    JS_PROP_INT32_DEF("DisplayHex", ImGuiColorEditFlags_DisplayHex, 0),
    JS_PROP_INT32_DEF("Uint8", ImGuiColorEditFlags_Uint8, 0),
    JS_PROP_INT32_DEF("Float", ImGuiColorEditFlags_Float, 0),
    JS_PROP_INT32_DEF("PickerHueBar", ImGuiColorEditFlags_PickerHueBar, 0),
    JS_PROP_INT32_DEF("PickerHueWheel", ImGuiColorEditFlags_PickerHueWheel, 0),
    JS_PROP_INT32_DEF("InputRGB", ImGuiColorEditFlags_InputRGB, 0),
    JS_PROP_INT32_DEF("InputHSV", ImGuiColorEditFlags_InputHSV, 0),
    JS_PROP_INT32_DEF("DefaultOptions_", ImGuiColorEditFlags_DefaultOptions_, 0),
    JS_PROP_INT32_DEF("DisplayMask_", ImGuiColorEditFlags_DisplayMask_, 0),
    JS_PROP_INT32_DEF("DataTypeMask_", ImGuiColorEditFlags_DataTypeMask_, 0),
    JS_PROP_INT32_DEF("PickerMask_", ImGuiColorEditFlags_PickerMask_, 0),
    JS_PROP_INT32_DEF("InputMask_", ImGuiColorEditFlags_InputMask_, 0),
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    JS_PROP_INT32_DEF("RGB", ImGuiColorEditFlags_RGB, 0),
    JS_PROP_INT32_DEF("HSV", ImGuiColorEditFlags_HSV, 0),
    JS_PROP_INT32_DEF("HEX", ImGuiColorEditFlags_HEX, 0),
#endif
};

static const JSCFunctionListEntry js_imgui_slider_flags[] = {
    JS_PROP_INT32_DEF("None", ImGuiSliderFlags_None, 0),
    JS_PROP_INT32_DEF("AlwaysClamp", ImGuiSliderFlags_AlwaysClamp, 0),
    JS_PROP_INT32_DEF("Logarithmic", ImGuiSliderFlags_Logarithmic, 0),
    JS_PROP_INT32_DEF("NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat, 0),
    JS_PROP_INT32_DEF("NoInput", ImGuiSliderFlags_NoInput, 0),
    JS_PROP_INT32_DEF("InvalidMask_", ImGuiSliderFlags_InvalidMask_, 0),
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    JS_PROP_INT32_DEF("ClampOnInput", ImGuiSliderFlags_ClampOnInput, 0),
#endif
};

static const JSCFunctionListEntry js_imgui_mousebutton[] = {
    JS_PROP_INT32_DEF("Left", ImGuiMouseButton_Left, 0),
    JS_PROP_INT32_DEF("Right", ImGuiMouseButton_Right, 0),
    JS_PROP_INT32_DEF("Middle", ImGuiMouseButton_Middle, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiMouseButton_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_mousecursor[] = {
    JS_PROP_INT32_DEF("None", ImGuiMouseCursor_None, 0),
    JS_PROP_INT32_DEF("Arrow", ImGuiMouseCursor_Arrow, 0),
    JS_PROP_INT32_DEF("TextInput", ImGuiMouseCursor_TextInput, 0),
    JS_PROP_INT32_DEF("ResizeAll", ImGuiMouseCursor_ResizeAll, 0),
    JS_PROP_INT32_DEF("ResizeNS", ImGuiMouseCursor_ResizeNS, 0),
    JS_PROP_INT32_DEF("ResizeEW", ImGuiMouseCursor_ResizeEW, 0),
    JS_PROP_INT32_DEF("ResizeNESW", ImGuiMouseCursor_ResizeNESW, 0),
    JS_PROP_INT32_DEF("ResizeNWSE", ImGuiMouseCursor_ResizeNWSE, 0),
    JS_PROP_INT32_DEF("Hand", ImGuiMouseCursor_Hand, 0),
    JS_PROP_INT32_DEF("NotAllowed", ImGuiMouseCursor_NotAllowed, 0),
    JS_PROP_INT32_DEF("COUNT", ImGuiMouseCursor_COUNT, 0),
};

static const JSCFunctionListEntry js_imgui_cond[] = {
    JS_PROP_INT32_DEF("None", ImGuiCond_None, 0),
    JS_PROP_INT32_DEF("Always", ImGuiCond_Always, 0),
    JS_PROP_INT32_DEF("Once", ImGuiCond_Once, 0),
    JS_PROP_INT32_DEF("FirstUseEver", ImGuiCond_FirstUseEver, 0),
    JS_PROP_INT32_DEF("Appearing", ImGuiCond_Appearing, 0),
};

#endif // defined(QUICKJS_IMGUI_CONSTANTS_HPP)
