#ifndef QUICKJS_IMGUI_CONSTANTS_HPP
#define QUICKJS_IMGUI_CONSTANTS_HPP

#define JS_PROP_CONSTANT(name, value) JS_PROP_INT64_DEF(name, value, JS_PROP_ENUMERABLE)

static const JSCFunctionListEntry js_imgui_window_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiWindowFlags_None),
    JS_PROP_CONSTANT("NoTitleBar", ImGuiWindowFlags_NoTitleBar),
    JS_PROP_CONSTANT("NoResize", ImGuiWindowFlags_NoResize),
    JS_PROP_CONSTANT("NoMove", ImGuiWindowFlags_NoMove),
    JS_PROP_CONSTANT("NoScrollbar", ImGuiWindowFlags_NoScrollbar),
    JS_PROP_CONSTANT("NoScrollWithMouse", ImGuiWindowFlags_NoScrollWithMouse),
    JS_PROP_CONSTANT("NoCollapse", ImGuiWindowFlags_NoCollapse),
    JS_PROP_CONSTANT("AlwaysAutoResize", ImGuiWindowFlags_AlwaysAutoResize),
    JS_PROP_CONSTANT("NoBackground", ImGuiWindowFlags_NoBackground),
    JS_PROP_CONSTANT("NoSavedSettings", ImGuiWindowFlags_NoSavedSettings),
    JS_PROP_CONSTANT("NoMouseInputs", ImGuiWindowFlags_NoMouseInputs),
    JS_PROP_CONSTANT("MenuBar", ImGuiWindowFlags_MenuBar),
    JS_PROP_CONSTANT("HorizontalScrollbar", ImGuiWindowFlags_HorizontalScrollbar),
    JS_PROP_CONSTANT("NoFocusOnAppearing", ImGuiWindowFlags_NoFocusOnAppearing),
    JS_PROP_CONSTANT("NoBringToFrontOnFocus", ImGuiWindowFlags_NoBringToFrontOnFocus),
    JS_PROP_CONSTANT("AlwaysVerticalScrollbar", ImGuiWindowFlags_AlwaysVerticalScrollbar),
    JS_PROP_CONSTANT("AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar),
    JS_PROP_CONSTANT("AlwaysUseWindowPadding", ImGuiWindowFlags_AlwaysUseWindowPadding),
    JS_PROP_CONSTANT("NoNavInputs", ImGuiWindowFlags_NoNavInputs),
    JS_PROP_CONSTANT("NoNavFocus", ImGuiWindowFlags_NoNavFocus),
    JS_PROP_CONSTANT("UnsavedDocument", ImGuiWindowFlags_UnsavedDocument),
    JS_PROP_CONSTANT("NoNav", ImGuiWindowFlags_NoNav),
    JS_PROP_CONSTANT("NoDecoration", ImGuiWindowFlags_NoDecoration),
    JS_PROP_CONSTANT("NoInputs", ImGuiWindowFlags_NoInputs),
    JS_PROP_CONSTANT("NavFlattened", ImGuiWindowFlags_NavFlattened),
    JS_PROP_CONSTANT("ChildWindow", ImGuiWindowFlags_ChildWindow),
    JS_PROP_CONSTANT("Tooltip", ImGuiWindowFlags_Tooltip),
    JS_PROP_CONSTANT("Popup", ImGuiWindowFlags_Popup),
    JS_PROP_CONSTANT("Modal", ImGuiWindowFlags_Modal),
    JS_PROP_CONSTANT("ChildMenu", ImGuiWindowFlags_ChildMenu),
};

static const JSCFunctionListEntry js_imgui_inputtext_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiInputTextFlags_None),
    JS_PROP_CONSTANT("CharsDecimal", ImGuiInputTextFlags_CharsDecimal),
    JS_PROP_CONSTANT("CharsHexadecimal", ImGuiInputTextFlags_CharsHexadecimal),
    JS_PROP_CONSTANT("CharsUppercase", ImGuiInputTextFlags_CharsUppercase),
    JS_PROP_CONSTANT("CharsNoBlank", ImGuiInputTextFlags_CharsNoBlank),
    JS_PROP_CONSTANT("AutoSelectAll", ImGuiInputTextFlags_AutoSelectAll),
    JS_PROP_CONSTANT("EnterReturnsTrue", ImGuiInputTextFlags_EnterReturnsTrue),
    JS_PROP_CONSTANT("CallbackCompletion", ImGuiInputTextFlags_CallbackCompletion),
    JS_PROP_CONSTANT("CallbackHistory", ImGuiInputTextFlags_CallbackHistory),
    JS_PROP_CONSTANT("CallbackAlways", ImGuiInputTextFlags_CallbackAlways),
    JS_PROP_CONSTANT("CallbackCharFilter", ImGuiInputTextFlags_CallbackCharFilter),
    JS_PROP_CONSTANT("AllowTabInput", ImGuiInputTextFlags_AllowTabInput),
    JS_PROP_CONSTANT("CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine),
    JS_PROP_CONSTANT("NoHorizontalScroll", ImGuiInputTextFlags_NoHorizontalScroll),
    JS_PROP_CONSTANT("AlwaysOverwrite", ImGuiInputTextFlags_AlwaysOverwrite),
    JS_PROP_CONSTANT("ReadOnly", ImGuiInputTextFlags_ReadOnly),
    JS_PROP_CONSTANT("Password", ImGuiInputTextFlags_Password),
    JS_PROP_CONSTANT("NoUndoRedo", ImGuiInputTextFlags_NoUndoRedo),
    JS_PROP_CONSTANT("CharsScientific", ImGuiInputTextFlags_CharsScientific),
    JS_PROP_CONSTANT("CallbackResize", ImGuiInputTextFlags_CallbackResize),
    JS_PROP_CONSTANT("CallbackEdit", ImGuiInputTextFlags_CallbackEdit),
};

static const JSCFunctionListEntry js_imgui_treenode_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTreeNodeFlags_None),
    JS_PROP_CONSTANT("Selected", ImGuiTreeNodeFlags_Selected),
    JS_PROP_CONSTANT("Framed", ImGuiTreeNodeFlags_Framed),
    JS_PROP_CONSTANT("AllowItemOverlap", ImGuiTreeNodeFlags_AllowItemOverlap),
    JS_PROP_CONSTANT("NoTreePushOnOpen", ImGuiTreeNodeFlags_NoTreePushOnOpen),
    JS_PROP_CONSTANT("NoAutoOpenOnLog", ImGuiTreeNodeFlags_NoAutoOpenOnLog),
    JS_PROP_CONSTANT("DefaultOpen", ImGuiTreeNodeFlags_DefaultOpen),
    JS_PROP_CONSTANT("OpenOnDoubleClick", ImGuiTreeNodeFlags_OpenOnDoubleClick),
    JS_PROP_CONSTANT("OpenOnArrow", ImGuiTreeNodeFlags_OpenOnArrow),
    JS_PROP_CONSTANT("Leaf", ImGuiTreeNodeFlags_Leaf),
    JS_PROP_CONSTANT("Bullet", ImGuiTreeNodeFlags_Bullet),
    JS_PROP_CONSTANT("FramePadding", ImGuiTreeNodeFlags_FramePadding),
    JS_PROP_CONSTANT("SpanAvailWidth", ImGuiTreeNodeFlags_SpanAvailWidth),
    JS_PROP_CONSTANT("SpanFullWidth", ImGuiTreeNodeFlags_SpanFullWidth),
    JS_PROP_CONSTANT("NavLeftJumpsBackHere", ImGuiTreeNodeFlags_NavLeftJumpsBackHere),
    JS_PROP_CONSTANT("CollapsingHeader", ImGuiTreeNodeFlags_CollapsingHeader),
};

static const JSCFunctionListEntry js_imgui_popup_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiPopupFlags_None),
    JS_PROP_CONSTANT("MouseButtonLeft", ImGuiPopupFlags_MouseButtonLeft),
    JS_PROP_CONSTANT("MouseButtonRight", ImGuiPopupFlags_MouseButtonRight),
    JS_PROP_CONSTANT("MouseButtonMiddle", ImGuiPopupFlags_MouseButtonMiddle),
    JS_PROP_CONSTANT("MouseButtonMask_", ImGuiPopupFlags_MouseButtonMask_),
    JS_PROP_CONSTANT("MouseButtonDefault_", ImGuiPopupFlags_MouseButtonDefault_),
    JS_PROP_CONSTANT("NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup),
    JS_PROP_CONSTANT("NoOpenOverItems", ImGuiPopupFlags_NoOpenOverItems),
    JS_PROP_CONSTANT("AnyPopupId", ImGuiPopupFlags_AnyPopupId),
    JS_PROP_CONSTANT("AnyPopupLevel", ImGuiPopupFlags_AnyPopupLevel),
    JS_PROP_CONSTANT("AnyPopup", ImGuiPopupFlags_AnyPopup),
};

static const JSCFunctionListEntry js_imgui_selectable_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiSelectableFlags_None),
    JS_PROP_CONSTANT("DontClosePopups", ImGuiSelectableFlags_DontClosePopups),
    JS_PROP_CONSTANT("SpanAllColumns", ImGuiSelectableFlags_SpanAllColumns),
    JS_PROP_CONSTANT("AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick),
    JS_PROP_CONSTANT("Disabled", ImGuiSelectableFlags_Disabled),
    JS_PROP_CONSTANT("AllowItemOverlap", ImGuiSelectableFlags_AllowItemOverlap),
};

static const JSCFunctionListEntry js_imgui_combo_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiComboFlags_None),
    JS_PROP_CONSTANT("PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft),
    JS_PROP_CONSTANT("HeightSmall", ImGuiComboFlags_HeightSmall),
    JS_PROP_CONSTANT("HeightRegular", ImGuiComboFlags_HeightRegular),
    JS_PROP_CONSTANT("HeightLarge", ImGuiComboFlags_HeightLarge),
    JS_PROP_CONSTANT("HeightLargest", ImGuiComboFlags_HeightLargest),
    JS_PROP_CONSTANT("NoArrowButton", ImGuiComboFlags_NoArrowButton),
    JS_PROP_CONSTANT("NoPreview", ImGuiComboFlags_NoPreview),
    JS_PROP_CONSTANT("HeightMask_", ImGuiComboFlags_HeightMask_),
};

static const JSCFunctionListEntry js_imgui_tabbar_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTabBarFlags_None),
    JS_PROP_CONSTANT("Reorderable", ImGuiTabBarFlags_Reorderable),
    JS_PROP_CONSTANT("AutoSelectNewTabs", ImGuiTabBarFlags_AutoSelectNewTabs),
    JS_PROP_CONSTANT("TabListPopupButton", ImGuiTabBarFlags_TabListPopupButton),
    JS_PROP_CONSTANT("NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton),
    JS_PROP_CONSTANT("NoTabListScrollingButtons", ImGuiTabBarFlags_NoTabListScrollingButtons),
    JS_PROP_CONSTANT("NoTooltip", ImGuiTabBarFlags_NoTooltip),
    JS_PROP_CONSTANT("FittingPolicyResizeDown", ImGuiTabBarFlags_FittingPolicyResizeDown),
    JS_PROP_CONSTANT("FittingPolicyScroll", ImGuiTabBarFlags_FittingPolicyScroll),
    JS_PROP_CONSTANT("FittingPolicyMask_", ImGuiTabBarFlags_FittingPolicyMask_),
    JS_PROP_CONSTANT("FittingPolicyDefault_", ImGuiTabBarFlags_FittingPolicyDefault_),
};

static const JSCFunctionListEntry js_imgui_tabitem_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTabItemFlags_None),
    JS_PROP_CONSTANT("UnsavedDocument", ImGuiTabItemFlags_UnsavedDocument),
    JS_PROP_CONSTANT("SetSelected", ImGuiTabItemFlags_SetSelected),
    JS_PROP_CONSTANT("NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton),
    JS_PROP_CONSTANT("NoPushId", ImGuiTabItemFlags_NoPushId),
    JS_PROP_CONSTANT("NoTooltip", ImGuiTabItemFlags_NoTooltip),
    JS_PROP_CONSTANT("NoReorder", ImGuiTabItemFlags_NoReorder),
    JS_PROP_CONSTANT("Leading", ImGuiTabItemFlags_Leading),
    JS_PROP_CONSTANT("Trailing", ImGuiTabItemFlags_Trailing),
};

static const JSCFunctionListEntry js_imgui_table_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTableFlags_None),
    JS_PROP_CONSTANT("Resizable", ImGuiTableFlags_Resizable),
    JS_PROP_CONSTANT("Reorderable", ImGuiTableFlags_Reorderable),
    JS_PROP_CONSTANT("Hideable", ImGuiTableFlags_Hideable),
    JS_PROP_CONSTANT("Sortable", ImGuiTableFlags_Sortable),
    JS_PROP_CONSTANT("NoSavedSettings", ImGuiTableFlags_NoSavedSettings),
    JS_PROP_CONSTANT("ContextMenuInBody", ImGuiTableFlags_ContextMenuInBody),
    JS_PROP_CONSTANT("RowBg", ImGuiTableFlags_RowBg),
    JS_PROP_CONSTANT("BordersInnerH", ImGuiTableFlags_BordersInnerH),
    JS_PROP_CONSTANT("BordersOuterH", ImGuiTableFlags_BordersOuterH),
    JS_PROP_CONSTANT("BordersInnerV", ImGuiTableFlags_BordersInnerV),
    JS_PROP_CONSTANT("BordersOuterV", ImGuiTableFlags_BordersOuterV),
    JS_PROP_CONSTANT("BordersH", ImGuiTableFlags_BordersH),
    JS_PROP_CONSTANT("BordersV", ImGuiTableFlags_BordersV),
    JS_PROP_CONSTANT("BordersInner", ImGuiTableFlags_BordersInner),
    JS_PROP_CONSTANT("BordersOuter", ImGuiTableFlags_BordersOuter),
    JS_PROP_CONSTANT("Borders", ImGuiTableFlags_Borders),
    JS_PROP_CONSTANT("NoBordersInBody", ImGuiTableFlags_NoBordersInBody),
    JS_PROP_CONSTANT("NoBordersInBodyUntilResize", ImGuiTableFlags_NoBordersInBodyUntilResize),
    JS_PROP_CONSTANT("SizingFixedFit", ImGuiTableFlags_SizingFixedFit),
    JS_PROP_CONSTANT("SizingFixedSame", ImGuiTableFlags_SizingFixedSame),
    JS_PROP_CONSTANT("SizingStretchProp", ImGuiTableFlags_SizingStretchProp),
    JS_PROP_CONSTANT("SizingStretchSame", ImGuiTableFlags_SizingStretchSame),
    JS_PROP_CONSTANT("NoHostExtendX", ImGuiTableFlags_NoHostExtendX),
    JS_PROP_CONSTANT("NoHostExtendY", ImGuiTableFlags_NoHostExtendY),
    JS_PROP_CONSTANT("NoKeepColumnsVisible", ImGuiTableFlags_NoKeepColumnsVisible),
    JS_PROP_CONSTANT("PreciseWidths", ImGuiTableFlags_PreciseWidths),
    JS_PROP_CONSTANT("NoClip", ImGuiTableFlags_NoClip),
    JS_PROP_CONSTANT("PadOuterX", ImGuiTableFlags_PadOuterX),
    JS_PROP_CONSTANT("NoPadOuterX", ImGuiTableFlags_NoPadOuterX),
    JS_PROP_CONSTANT("NoPadInnerX", ImGuiTableFlags_NoPadInnerX),
    JS_PROP_CONSTANT("ScrollX", ImGuiTableFlags_ScrollX),
    JS_PROP_CONSTANT("ScrollY", ImGuiTableFlags_ScrollY),
    JS_PROP_CONSTANT("SortMulti", ImGuiTableFlags_SortMulti),
    JS_PROP_CONSTANT("SortTristate", ImGuiTableFlags_SortTristate),
    JS_PROP_CONSTANT("SizingMask_", ImGuiTableFlags_SizingMask_),
};

static const JSCFunctionListEntry js_imgui_tablecolumn_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTableColumnFlags_None),
    JS_PROP_CONSTANT("Disabled", ImGuiTableColumnFlags_Disabled),
    JS_PROP_CONSTANT("DefaultHide", ImGuiTableColumnFlags_DefaultHide),
    JS_PROP_CONSTANT("DefaultSort", ImGuiTableColumnFlags_DefaultSort),
    JS_PROP_CONSTANT("WidthStretch", ImGuiTableColumnFlags_WidthStretch),
    JS_PROP_CONSTANT("WidthFixed", ImGuiTableColumnFlags_WidthFixed),
    JS_PROP_CONSTANT("NoResize", ImGuiTableColumnFlags_NoResize),
    JS_PROP_CONSTANT("NoReorder", ImGuiTableColumnFlags_NoReorder),
    JS_PROP_CONSTANT("NoHide", ImGuiTableColumnFlags_NoHide),
    JS_PROP_CONSTANT("NoClip", ImGuiTableColumnFlags_NoClip),
    JS_PROP_CONSTANT("NoSort", ImGuiTableColumnFlags_NoSort),
    JS_PROP_CONSTANT("NoSortAscending", ImGuiTableColumnFlags_NoSortAscending),
    JS_PROP_CONSTANT("NoSortDescending", ImGuiTableColumnFlags_NoSortDescending),
    JS_PROP_CONSTANT("NoHeaderLabel", ImGuiTableColumnFlags_NoHeaderLabel),
    JS_PROP_CONSTANT("NoHeaderWidth", ImGuiTableColumnFlags_NoHeaderWidth),
    JS_PROP_CONSTANT("PreferSortAscending", ImGuiTableColumnFlags_PreferSortAscending),
    JS_PROP_CONSTANT("PreferSortDescending", ImGuiTableColumnFlags_PreferSortDescending),
    JS_PROP_CONSTANT("IndentEnable", ImGuiTableColumnFlags_IndentEnable),
    JS_PROP_CONSTANT("IndentDisable", ImGuiTableColumnFlags_IndentDisable),
    JS_PROP_CONSTANT("IsEnabled", ImGuiTableColumnFlags_IsEnabled),
    JS_PROP_CONSTANT("IsVisible", ImGuiTableColumnFlags_IsVisible),
    JS_PROP_CONSTANT("IsSorted", ImGuiTableColumnFlags_IsSorted),
    JS_PROP_CONSTANT("IsHovered", ImGuiTableColumnFlags_IsHovered),
    JS_PROP_CONSTANT("WidthMask_", ImGuiTableColumnFlags_WidthMask_),
    JS_PROP_CONSTANT("IndentMask_", ImGuiTableColumnFlags_IndentMask_),
    JS_PROP_CONSTANT("StatusMask_", ImGuiTableColumnFlags_StatusMask_),
    JS_PROP_CONSTANT("NoDirectResize_", ImGuiTableColumnFlags_NoDirectResize_),
};

static const JSCFunctionListEntry js_imgui_tablerow_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiTableRowFlags_None),
    JS_PROP_CONSTANT("Headers", ImGuiTableRowFlags_Headers),
};

static const JSCFunctionListEntry js_imgui_tablebgtarget[] = {
    JS_PROP_CONSTANT("None", ImGuiTableBgTarget_None),
    JS_PROP_CONSTANT("RowBg0", ImGuiTableBgTarget_RowBg0),
    JS_PROP_CONSTANT("RowBg1", ImGuiTableBgTarget_RowBg1),
    JS_PROP_CONSTANT("CellBg", ImGuiTableBgTarget_CellBg),
};

static const JSCFunctionListEntry js_imgui_focused_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiFocusedFlags_None),
    JS_PROP_CONSTANT("ChildWindows", ImGuiFocusedFlags_ChildWindows),
    JS_PROP_CONSTANT("RootWindow", ImGuiFocusedFlags_RootWindow),
    JS_PROP_CONSTANT("AnyWindow", ImGuiFocusedFlags_AnyWindow),
    JS_PROP_CONSTANT("RootAndChildWindows", ImGuiFocusedFlags_RootAndChildWindows),
};

static const JSCFunctionListEntry js_imgui_hovered_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiHoveredFlags_None),
    JS_PROP_CONSTANT("ChildWindows", ImGuiHoveredFlags_ChildWindows),
    JS_PROP_CONSTANT("RootWindow", ImGuiHoveredFlags_RootWindow),
    JS_PROP_CONSTANT("AnyWindow", ImGuiHoveredFlags_AnyWindow),
    JS_PROP_CONSTANT("AllowWhenBlockedByPopup", ImGuiHoveredFlags_AllowWhenBlockedByPopup),
    JS_PROP_CONSTANT("AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem),
    JS_PROP_CONSTANT("AllowWhenOverlapped", ImGuiHoveredFlags_AllowWhenOverlapped),
    JS_PROP_CONSTANT("AllowWhenDisabled", ImGuiHoveredFlags_AllowWhenDisabled),
    JS_PROP_CONSTANT("RectOnly", ImGuiHoveredFlags_RectOnly),
    JS_PROP_CONSTANT("RootAndChildWindows", ImGuiHoveredFlags_RootAndChildWindows),
};

static const JSCFunctionListEntry js_imgui_dragdrop_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiDragDropFlags_None),
    JS_PROP_CONSTANT("SourceNoPreviewTooltip", ImGuiDragDropFlags_SourceNoPreviewTooltip),
    JS_PROP_CONSTANT("SourceNoDisableHover", ImGuiDragDropFlags_SourceNoDisableHover),
    JS_PROP_CONSTANT("SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers),
    JS_PROP_CONSTANT("SourceAllowNullID", ImGuiDragDropFlags_SourceAllowNullID),
    JS_PROP_CONSTANT("SourceExtern", ImGuiDragDropFlags_SourceExtern),
    JS_PROP_CONSTANT("SourceAutoExpirePayload", ImGuiDragDropFlags_SourceAutoExpirePayload),
    JS_PROP_CONSTANT("AcceptBeforeDelivery", ImGuiDragDropFlags_AcceptBeforeDelivery),
    JS_PROP_CONSTANT("AcceptNoDrawDefaultRect", ImGuiDragDropFlags_AcceptNoDrawDefaultRect),
    JS_PROP_CONSTANT("AcceptNoPreviewTooltip", ImGuiDragDropFlags_AcceptNoPreviewTooltip),
    JS_PROP_CONSTANT("AcceptPeekOnly", ImGuiDragDropFlags_AcceptPeekOnly),
};

static const JSCFunctionListEntry js_imgui_datatype[] = {
    JS_PROP_CONSTANT("S8", ImGuiDataType_S8),
    JS_PROP_CONSTANT("U8", ImGuiDataType_U8),
    JS_PROP_CONSTANT("S16", ImGuiDataType_S16),
    JS_PROP_CONSTANT("U16", ImGuiDataType_U16),
    JS_PROP_CONSTANT("S32", ImGuiDataType_S32),
    JS_PROP_CONSTANT("U32", ImGuiDataType_U32),
    JS_PROP_CONSTANT("S64", ImGuiDataType_S64),
    JS_PROP_CONSTANT("U64", ImGuiDataType_U64),
    JS_PROP_CONSTANT("Float", ImGuiDataType_Float),
    JS_PROP_CONSTANT("Double", ImGuiDataType_Double),
    JS_PROP_CONSTANT("COUNT", ImGuiDataType_COUNT),
};

static const JSCFunctionListEntry js_imgui_dir[] = {
    JS_PROP_CONSTANT("None", ImGuiDir_None),
    JS_PROP_CONSTANT("Left", ImGuiDir_Left),
    JS_PROP_CONSTANT("Right", ImGuiDir_Right),
    JS_PROP_CONSTANT("Up", ImGuiDir_Up),
    JS_PROP_CONSTANT("Down", ImGuiDir_Down),
    JS_PROP_CONSTANT("COUNT", ImGuiDir_COUNT),
};

static const JSCFunctionListEntry js_imgui_sortdirection[] = {
    JS_PROP_CONSTANT("None", ImGuiSortDirection_None),
    JS_PROP_CONSTANT("Ascending", ImGuiSortDirection_Ascending),
    JS_PROP_CONSTANT("Descending", ImGuiSortDirection_Descending),
};

static const JSCFunctionListEntry js_imgui_key[] = {
    JS_PROP_CONSTANT("Tab", ImGuiKey_Tab),
    JS_PROP_CONSTANT("LeftArrow", ImGuiKey_LeftArrow),
    JS_PROP_CONSTANT("RightArrow", ImGuiKey_RightArrow),
    JS_PROP_CONSTANT("UpArrow", ImGuiKey_UpArrow),
    JS_PROP_CONSTANT("DownArrow", ImGuiKey_DownArrow),
    JS_PROP_CONSTANT("PageUp", ImGuiKey_PageUp),
    JS_PROP_CONSTANT("PageDown", ImGuiKey_PageDown),
    JS_PROP_CONSTANT("Home", ImGuiKey_Home),
    JS_PROP_CONSTANT("End", ImGuiKey_End),
    JS_PROP_CONSTANT("Insert", ImGuiKey_Insert),
    JS_PROP_CONSTANT("Delete", ImGuiKey_Delete),
    JS_PROP_CONSTANT("Backspace", ImGuiKey_Backspace),
    JS_PROP_CONSTANT("Space", ImGuiKey_Space),
    JS_PROP_CONSTANT("Enter", ImGuiKey_Enter),
    JS_PROP_CONSTANT("Escape", ImGuiKey_Escape),
    JS_PROP_CONSTANT("KeyPadEnter", ImGuiKey_KeyPadEnter),
    JS_PROP_CONSTANT("A", ImGuiKey_A),
    JS_PROP_CONSTANT("C", ImGuiKey_C),
    JS_PROP_CONSTANT("V", ImGuiKey_V),
    JS_PROP_CONSTANT("X", ImGuiKey_X),
    JS_PROP_CONSTANT("Y", ImGuiKey_Y),
    JS_PROP_CONSTANT("Z", ImGuiKey_Z),
    JS_PROP_CONSTANT("COUNT", ImGuiKey_COUNT),
};

static const JSCFunctionListEntry js_imgui_keymod_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiModFlags_None),
    JS_PROP_CONSTANT("Ctrl", ImGuiModFlags_Ctrl),
    JS_PROP_CONSTANT("Shift", ImGuiModFlags_Shift),
    JS_PROP_CONSTANT("Alt", ImGuiModFlags_Alt),
    JS_PROP_CONSTANT("Super", ImGuiModFlags_Super),
};

static const JSCFunctionListEntry js_imgui_navinput[] = {
    JS_PROP_CONSTANT("Activate", ImGuiNavInput_Activate),     JS_PROP_CONSTANT("Cancel", ImGuiNavInput_Cancel),           JS_PROP_CONSTANT("Input", ImGuiNavInput_Input),         JS_PROP_CONSTANT("Menu", ImGuiNavInput_Menu),
    JS_PROP_CONSTANT("DpadLeft", ImGuiNavInput_DpadLeft),     JS_PROP_CONSTANT("DpadRight", ImGuiNavInput_DpadRight),     JS_PROP_CONSTANT("DpadUp", ImGuiNavInput_DpadUp),       JS_PROP_CONSTANT("DpadDown", ImGuiNavInput_DpadDown),
    JS_PROP_CONSTANT("LStickLeft", ImGuiNavInput_LStickLeft), JS_PROP_CONSTANT("LStickRight", ImGuiNavInput_LStickRight), JS_PROP_CONSTANT("LStickUp", ImGuiNavInput_LStickUp),   JS_PROP_CONSTANT("LStickDown", ImGuiNavInput_LStickDown),
    JS_PROP_CONSTANT("FocusPrev", ImGuiNavInput_FocusPrev),   JS_PROP_CONSTANT("FocusNext", ImGuiNavInput_FocusNext),     JS_PROP_CONSTANT("TweakSlow", ImGuiNavInput_TweakSlow), JS_PROP_CONSTANT("TweakFast", ImGuiNavInput_TweakFast),
    JS_PROP_CONSTANT("DpadLeft", ImGuiNavInput_DpadLeft),     JS_PROP_CONSTANT("DpadRight", ImGuiNavInput_DpadRight),     JS_PROP_CONSTANT("DpadUp", ImGuiNavInput_DpadUp),       JS_PROP_CONSTANT("DpadDown", ImGuiNavInput_DpadDown),
    JS_PROP_CONSTANT("COUNT", ImGuiNavInput_COUNT), // JS_PROP_CONSTANT("InternalStart_", ImGuiNavInput_InternalStart_),
};

static const JSCFunctionListEntry js_imgui_config_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiConfigFlags_None),
    JS_PROP_CONSTANT("NavEnableKeyboard", ImGuiConfigFlags_NavEnableKeyboard),
    JS_PROP_CONSTANT("NavEnableGamepad", ImGuiConfigFlags_NavEnableGamepad),
    JS_PROP_CONSTANT("NavEnableSetMousePos", ImGuiConfigFlags_NavEnableSetMousePos),
    JS_PROP_CONSTANT("NavNoCaptureKeyboard", ImGuiConfigFlags_NavNoCaptureKeyboard),
    JS_PROP_CONSTANT("NoMouse", ImGuiConfigFlags_NoMouse),
    JS_PROP_CONSTANT("NoMouseCursorChange", ImGuiConfigFlags_NoMouseCursorChange),
    JS_PROP_CONSTANT("IsSRGB", ImGuiConfigFlags_IsSRGB),
    JS_PROP_CONSTANT("IsTouchScreen", ImGuiConfigFlags_IsTouchScreen),
};

static const JSCFunctionListEntry js_imgui_backend_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiBackendFlags_None),
    JS_PROP_CONSTANT("HasGamepad", ImGuiBackendFlags_HasGamepad),
    JS_PROP_CONSTANT("HasMouseCursors", ImGuiBackendFlags_HasMouseCursors),
    JS_PROP_CONSTANT("HasSetMousePos", ImGuiBackendFlags_HasSetMousePos),
    JS_PROP_CONSTANT("RendererHasVtxOffset", ImGuiBackendFlags_RendererHasVtxOffset),
};

static const JSCFunctionListEntry js_imgui_col[] = {
    JS_PROP_CONSTANT("Text", ImGuiCol_Text),
    JS_PROP_CONSTANT("TextDisabled", ImGuiCol_TextDisabled),
    JS_PROP_CONSTANT("WindowBg", ImGuiCol_WindowBg),
    JS_PROP_CONSTANT("ChildBg", ImGuiCol_ChildBg),
    JS_PROP_CONSTANT("PopupBg", ImGuiCol_PopupBg),
    JS_PROP_CONSTANT("Border", ImGuiCol_Border),
    JS_PROP_CONSTANT("BorderShadow", ImGuiCol_BorderShadow),
    JS_PROP_CONSTANT("FrameBg", ImGuiCol_FrameBg),
    JS_PROP_CONSTANT("FrameBgHovered", ImGuiCol_FrameBgHovered),
    JS_PROP_CONSTANT("FrameBgActive", ImGuiCol_FrameBgActive),
    JS_PROP_CONSTANT("TitleBg", ImGuiCol_TitleBg),
    JS_PROP_CONSTANT("TitleBgActive", ImGuiCol_TitleBgActive),
    JS_PROP_CONSTANT("TitleBgCollapsed", ImGuiCol_TitleBgCollapsed),
    JS_PROP_CONSTANT("MenuBarBg", ImGuiCol_MenuBarBg),
    JS_PROP_CONSTANT("ScrollbarBg", ImGuiCol_ScrollbarBg),
    JS_PROP_CONSTANT("ScrollbarGrab", ImGuiCol_ScrollbarGrab),
    JS_PROP_CONSTANT("ScrollbarGrabHovered", ImGuiCol_ScrollbarGrabHovered),
    JS_PROP_CONSTANT("ScrollbarGrabActive", ImGuiCol_ScrollbarGrabActive),
    JS_PROP_CONSTANT("CheckMark", ImGuiCol_CheckMark),
    JS_PROP_CONSTANT("SliderGrab", ImGuiCol_SliderGrab),
    JS_PROP_CONSTANT("SliderGrabActive", ImGuiCol_SliderGrabActive),
    JS_PROP_CONSTANT("Button", ImGuiCol_Button),
    JS_PROP_CONSTANT("ButtonHovered", ImGuiCol_ButtonHovered),
    JS_PROP_CONSTANT("ButtonActive", ImGuiCol_ButtonActive),
    JS_PROP_CONSTANT("Header", ImGuiCol_Header),
    JS_PROP_CONSTANT("HeaderHovered", ImGuiCol_HeaderHovered),
    JS_PROP_CONSTANT("HeaderActive", ImGuiCol_HeaderActive),
    JS_PROP_CONSTANT("Separator", ImGuiCol_Separator),
    JS_PROP_CONSTANT("SeparatorHovered", ImGuiCol_SeparatorHovered),
    JS_PROP_CONSTANT("SeparatorActive", ImGuiCol_SeparatorActive),
    JS_PROP_CONSTANT("ResizeGrip", ImGuiCol_ResizeGrip),
    JS_PROP_CONSTANT("ResizeGripHovered", ImGuiCol_ResizeGripHovered),
    JS_PROP_CONSTANT("ResizeGripActive", ImGuiCol_ResizeGripActive),
    JS_PROP_CONSTANT("Tab", ImGuiCol_Tab),
    JS_PROP_CONSTANT("TabHovered", ImGuiCol_TabHovered),
    JS_PROP_CONSTANT("TabActive", ImGuiCol_TabActive),
    JS_PROP_CONSTANT("TabUnfocused", ImGuiCol_TabUnfocused),
    JS_PROP_CONSTANT("TabUnfocusedActive", ImGuiCol_TabUnfocusedActive),
    JS_PROP_CONSTANT("PlotLines", ImGuiCol_PlotLines),
    JS_PROP_CONSTANT("PlotLinesHovered", ImGuiCol_PlotLinesHovered),
    JS_PROP_CONSTANT("PlotHistogram", ImGuiCol_PlotHistogram),
    JS_PROP_CONSTANT("PlotHistogramHovered", ImGuiCol_PlotHistogramHovered),
    JS_PROP_CONSTANT("TableHeaderBg", ImGuiCol_TableHeaderBg),
    JS_PROP_CONSTANT("TableBorderStrong", ImGuiCol_TableBorderStrong),
    JS_PROP_CONSTANT("TableBorderLight", ImGuiCol_TableBorderLight),
    JS_PROP_CONSTANT("TableRowBg", ImGuiCol_TableRowBg),
    JS_PROP_CONSTANT("TableRowBgAlt", ImGuiCol_TableRowBgAlt),
    JS_PROP_CONSTANT("TextSelectedBg", ImGuiCol_TextSelectedBg),
    JS_PROP_CONSTANT("DragDropTarget", ImGuiCol_DragDropTarget),
    JS_PROP_CONSTANT("NavHighlight", ImGuiCol_NavHighlight),
    JS_PROP_CONSTANT("NavWindowingHighlight", ImGuiCol_NavWindowingHighlight),
    JS_PROP_CONSTANT("NavWindowingDimBg", ImGuiCol_NavWindowingDimBg),
    JS_PROP_CONSTANT("ModalWindowDimBg", ImGuiCol_ModalWindowDimBg),
    JS_PROP_CONSTANT("COUNT", ImGuiCol_COUNT),
};

static const JSCFunctionListEntry js_imgui_stylevar[] = {
    JS_PROP_CONSTANT("Alpha", ImGuiStyleVar_Alpha),
    JS_PROP_CONSTANT("DisabledAlpha", ImGuiStyleVar_DisabledAlpha),
    JS_PROP_CONSTANT("WindowPadding", ImGuiStyleVar_WindowPadding),
    JS_PROP_CONSTANT("WindowRounding", ImGuiStyleVar_WindowRounding),
    JS_PROP_CONSTANT("WindowBorderSize", ImGuiStyleVar_WindowBorderSize),
    JS_PROP_CONSTANT("WindowMinSize", ImGuiStyleVar_WindowMinSize),
    JS_PROP_CONSTANT("WindowTitleAlign", ImGuiStyleVar_WindowTitleAlign),
    JS_PROP_CONSTANT("ChildRounding", ImGuiStyleVar_ChildRounding),
    JS_PROP_CONSTANT("ChildBorderSize", ImGuiStyleVar_ChildBorderSize),
    JS_PROP_CONSTANT("PopupRounding", ImGuiStyleVar_PopupRounding),
    JS_PROP_CONSTANT("PopupBorderSize", ImGuiStyleVar_PopupBorderSize),
    JS_PROP_CONSTANT("FramePadding", ImGuiStyleVar_FramePadding),
    JS_PROP_CONSTANT("FrameRounding", ImGuiStyleVar_FrameRounding),
    JS_PROP_CONSTANT("FrameBorderSize", ImGuiStyleVar_FrameBorderSize),
    JS_PROP_CONSTANT("ItemSpacing", ImGuiStyleVar_ItemSpacing),
    JS_PROP_CONSTANT("ItemInnerSpacing", ImGuiStyleVar_ItemInnerSpacing),
    JS_PROP_CONSTANT("IndentSpacing", ImGuiStyleVar_IndentSpacing),
    JS_PROP_CONSTANT("CellPadding", ImGuiStyleVar_CellPadding),
    JS_PROP_CONSTANT("ScrollbarSize", ImGuiStyleVar_ScrollbarSize),
    JS_PROP_CONSTANT("ScrollbarRounding", ImGuiStyleVar_ScrollbarRounding),
    JS_PROP_CONSTANT("GrabMinSize", ImGuiStyleVar_GrabMinSize),
    JS_PROP_CONSTANT("GrabRounding", ImGuiStyleVar_GrabRounding),
    JS_PROP_CONSTANT("TabRounding", ImGuiStyleVar_TabRounding),
    JS_PROP_CONSTANT("ButtonTextAlign", ImGuiStyleVar_ButtonTextAlign),
    JS_PROP_CONSTANT("SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign),
    JS_PROP_CONSTANT("COUNT", ImGuiStyleVar_COUNT),
};

static const JSCFunctionListEntry js_imgui_button_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiButtonFlags_None),
    JS_PROP_CONSTANT("MouseButtonLeft", ImGuiButtonFlags_MouseButtonLeft),
    JS_PROP_CONSTANT("MouseButtonRight", ImGuiButtonFlags_MouseButtonRight),
    JS_PROP_CONSTANT("MouseButtonMiddle", ImGuiButtonFlags_MouseButtonMiddle),
    JS_PROP_CONSTANT("MouseButtonMask_", ImGuiButtonFlags_MouseButtonMask_),
    JS_PROP_CONSTANT("MouseButtonDefault_", ImGuiButtonFlags_MouseButtonDefault_),
};

static const JSCFunctionListEntry js_imgui_coloredit_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiColorEditFlags_None),
    JS_PROP_CONSTANT("NoAlpha", ImGuiColorEditFlags_NoAlpha),
    JS_PROP_CONSTANT("NoPicker", ImGuiColorEditFlags_NoPicker),
    JS_PROP_CONSTANT("NoOptions", ImGuiColorEditFlags_NoOptions),
    JS_PROP_CONSTANT("NoSmallPreview", ImGuiColorEditFlags_NoSmallPreview),
    JS_PROP_CONSTANT("NoInputs", ImGuiColorEditFlags_NoInputs),
    JS_PROP_CONSTANT("NoTooltip", ImGuiColorEditFlags_NoTooltip),
    JS_PROP_CONSTANT("NoLabel", ImGuiColorEditFlags_NoLabel),
    JS_PROP_CONSTANT("NoSidePreview", ImGuiColorEditFlags_NoSidePreview),
    JS_PROP_CONSTANT("NoDragDrop", ImGuiColorEditFlags_NoDragDrop),
    JS_PROP_CONSTANT("NoBorder", ImGuiColorEditFlags_NoBorder),
    JS_PROP_CONSTANT("AlphaBar", ImGuiColorEditFlags_AlphaBar),
    JS_PROP_CONSTANT("AlphaPreview", ImGuiColorEditFlags_AlphaPreview),
    JS_PROP_CONSTANT("AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf),
    JS_PROP_CONSTANT("HDR", ImGuiColorEditFlags_HDR),
    JS_PROP_CONSTANT("DisplayRGB", ImGuiColorEditFlags_DisplayRGB),
    JS_PROP_CONSTANT("DisplayHSV", ImGuiColorEditFlags_DisplayHSV),
    JS_PROP_CONSTANT("DisplayHex", ImGuiColorEditFlags_DisplayHex),
    JS_PROP_CONSTANT("Uint8", ImGuiColorEditFlags_Uint8),
    JS_PROP_CONSTANT("Float", ImGuiColorEditFlags_Float),
    JS_PROP_CONSTANT("PickerHueBar", ImGuiColorEditFlags_PickerHueBar),
    JS_PROP_CONSTANT("PickerHueWheel", ImGuiColorEditFlags_PickerHueWheel),
    JS_PROP_CONSTANT("InputRGB", ImGuiColorEditFlags_InputRGB),
    JS_PROP_CONSTANT("InputHSV", ImGuiColorEditFlags_InputHSV),
    JS_PROP_CONSTANT("DefaultOptions_", ImGuiColorEditFlags_DefaultOptions_),
    JS_PROP_CONSTANT("DisplayMask_", ImGuiColorEditFlags_DisplayMask_),
    JS_PROP_CONSTANT("DataTypeMask_", ImGuiColorEditFlags_DataTypeMask_),
    JS_PROP_CONSTANT("PickerMask_", ImGuiColorEditFlags_PickerMask_),
    JS_PROP_CONSTANT("InputMask_", ImGuiColorEditFlags_InputMask_),
#if 0 // IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    JS_PROP_CONSTANT("RGB", ImGuiColorEditFlags_RGB),
    JS_PROP_CONSTANT("HSV", ImGuiColorEditFlags_HSV),
    JS_PROP_CONSTANT("HEX", ImGuiColorEditFlags_HEX),
#endif
};

static const JSCFunctionListEntry js_imgui_slider_flags[] = {
    JS_PROP_CONSTANT("None", ImGuiSliderFlags_None),
    JS_PROP_CONSTANT("AlwaysClamp", ImGuiSliderFlags_AlwaysClamp),
    JS_PROP_CONSTANT("Logarithmic", ImGuiSliderFlags_Logarithmic),
    JS_PROP_CONSTANT("NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat),
    JS_PROP_CONSTANT("NoInput", ImGuiSliderFlags_NoInput),
    JS_PROP_CONSTANT("InvalidMask_", ImGuiSliderFlags_InvalidMask_),
#if 0 // IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    JS_PROP_CONSTANT("ClampOnInput", ImGuiSliderFlags_ClampOnInput),
#endif
};

static const JSCFunctionListEntry js_imgui_mousebutton[] = {
    JS_PROP_CONSTANT("Left", ImGuiMouseButton_Left),
    JS_PROP_CONSTANT("Right", ImGuiMouseButton_Right),
    JS_PROP_CONSTANT("Middle", ImGuiMouseButton_Middle),
    JS_PROP_CONSTANT("COUNT", ImGuiMouseButton_COUNT),
};

static const JSCFunctionListEntry js_imgui_mousecursor[] = {
    JS_PROP_CONSTANT("None", ImGuiMouseCursor_None),
    JS_PROP_CONSTANT("Arrow", ImGuiMouseCursor_Arrow),
    JS_PROP_CONSTANT("TextInput", ImGuiMouseCursor_TextInput),
    JS_PROP_CONSTANT("ResizeAll", ImGuiMouseCursor_ResizeAll),
    JS_PROP_CONSTANT("ResizeNS", ImGuiMouseCursor_ResizeNS),
    JS_PROP_CONSTANT("ResizeEW", ImGuiMouseCursor_ResizeEW),
    JS_PROP_CONSTANT("ResizeNESW", ImGuiMouseCursor_ResizeNESW),
    JS_PROP_CONSTANT("ResizeNWSE", ImGuiMouseCursor_ResizeNWSE),
    JS_PROP_CONSTANT("Hand", ImGuiMouseCursor_Hand),
    JS_PROP_CONSTANT("NotAllowed", ImGuiMouseCursor_NotAllowed),
    JS_PROP_CONSTANT("COUNT", ImGuiMouseCursor_COUNT),
};

static const JSCFunctionListEntry js_imgui_cond[] = {
    JS_PROP_CONSTANT("None", ImGuiCond_None),
    JS_PROP_CONSTANT("Always", ImGuiCond_Always),
    JS_PROP_CONSTANT("Once", ImGuiCond_Once),
    JS_PROP_CONSTANT("FirstUseEver", ImGuiCond_FirstUseEver),
    JS_PROP_CONSTANT("Appearing", ImGuiCond_Appearing),
};

#endif // defined(QUICKJS_IMGUI_CONSTANTS_HPP)
